### ISSUE TITLE
Open URL in browser

### ISSUE THREAD

**Issue by davidbrochart** [asphalt-framework/asphalt-web#30]
Would it make sense to have a configuration parameter that would open a browser window at a given URL based on the host URL, after the server has been launched? Something like:
```yaml
component:
  type: fastapi
  components:
    myroot:
      type: dynamic:WebRootComponent
      open_url: my/url
```
